/*
 * MetricMQ Security Demo: Signed Publisher (ESP32-S3 Board #1)
 * 
 * HEADLINE FEATURE: Every message is cryptographically signed with Ed25519.
 * The broker REJECTS unsigned messages on secure/ topics.
 * Only 64 bytes of overhead per message — not 200+ like JWT.
 *
 * Demonstrates:
 *   - Ed25519 signed publish (libsodium on ESP32)
 *   - Secure topics (secure/ prefix) — unsigned = rejected
 *   - Normal unsigned topics for comparison
 *   - Built-in temperature sensor (ESP32-S3)
 *   - Binary protocol (40% smaller than RESP)
 *   - Exactly-once delivery
 *   - Auto-reconnect
 *
 * Hardware: ESP32-S3-DevKitC-1-N16R8 (built-in temp sensor, capacitive touch)
 *
 * SETUP:
 *   1. Run metricmq-keygen.exe to generate keys for this device
 *   2. Paste the generated DEVICE_SECRET_KEY / DEVICE_KEY_ID below
 *   3. Register the public key in the broker (see keygen output)
 *   4. Set WiFi credentials and broker IP
 *   5. Upload to Board #1
 */

#include <WiFi.h>
#include <MetricMQ.h>

// ===== CONFIGURATION =====
const char* WIFI_SSID      = "YourWiFiSSID";
const char* WIFI_PASSWORD   = "YourWiFiPassword";
const char* BROKER_HOST     = "192.168.1.100";
const uint16_t BROKER_PORT  = 6379;

// ===== ED25519 KEYS (generated by metricmq-keygen.exe) =====
// Run: .\build\Release\metricmq-keygen.exe "sensor_node_1" "secure/sensors/*"
// Then paste the output here:
const uint32_t DEVICE_KEY_ID = 1;  // Replace with keygen output

// PLACEHOLDER — replace with keygen output!
// These are example keys that will NOT work with your broker.
const uint8_t DEVICE_SECRET_KEY[64] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00
};

const uint8_t DEVICE_PUBLIC_KEY[32] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
// ===========================================================

// LED (ESP32-S3 built-in)
#ifdef RGB_BUILTIN
  #define LED_PIN RGB_BUILTIN
#else
  #define LED_PIN 48
#endif

// Touch pin (ESP32-S3 capacitive touch)
#define TOUCH_PIN T1  // GPIO 1

MetricMQClient mqClient;

unsigned long lastSecurePublish = 0;
unsigned long lastUnsignedPublish = 0;
unsigned long lastHeartbeat = 0;
unsigned long startTime = 0;

uint32_t signedCount = 0;
uint32_t unsignedCount = 0;
uint32_t rejectCount = 0;
unsigned long totalSignTimeUs = 0;

// ESP32-S3 internal temperature sensor
#ifdef __cplusplus
extern "C" {
#endif
float temperatureRead();
#ifdef __cplusplus
}
#endif

void setup() {
    Serial.begin(115200);
    delay(1000);

    Serial.println("\n╔══════════════════════════════════════════════════╗");
    Serial.println("║  MetricMQ SECURITY Demo — SIGNED PUBLISHER       ║");
    Serial.println("║  Ed25519 Signatures | Secure Topics | ESP32-S3   ║");
    Serial.println("╚══════════════════════════════════════════════════╝\n");

    if (psramFound()) {
        Serial.printf("PSRAM: %u bytes available\n", ESP.getPsramSize());
    }

    // LED
    pinMode(LED_PIN, OUTPUT);

    // WiFi
    WiFi.mode(WIFI_STA);
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    Serial.printf("Connecting to WiFi '%s'", WIFI_SSID);
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
    Serial.printf(" Connected! IP: %s\n", WiFi.localIP().toString().c_str());

    // MetricMQ setup
    mqClient.begin(BROKER_HOST, BROKER_PORT);
    mqClient.setClientId("esp32s3_secure_pub");
    mqClient.enableExactlyOnce(true);
    mqClient.setKeepAlive(15);

    // Load Ed25519 signing key
    mqClient.setSigningKey(DEVICE_SECRET_KEY, DEVICE_KEY_ID);

    // Connect
    Serial.printf("Connecting to broker at %s:%d...\n", BROKER_HOST, BROKER_PORT);
    if (mqClient.connect()) {
        Serial.println(">>> CONNECTED (binary protocol v1)");
        Serial.println(">>> Ed25519 signing: ENABLED");
        Serial.printf(">>> Key ID: %u\n", DEVICE_KEY_ID);
    } else {
        Serial.println("!!! Connection failed — retrying in loop()");
    }

    startTime = millis();
    Serial.println("\n--- Demo running: signed + unsigned publishes ---\n");
}

void loop() {
    mqClient.loop();

    if (!mqClient.isConnected()) {
        Serial.println("Reconnecting...");
        if (mqClient.connect()) {
            Serial.println(">>> Reconnected!");
        } else {
            delay(3000);
            return;
        }
    }

    unsigned long now = millis();

    // === SIGNED PUBLISH to secure/ topic (every 3s) ===
    if (now - lastSecurePublish >= 3000) {
        lastSecurePublish = now;

        float temp = temperatureRead();  // Built-in temp sensor
        int touchVal = touchRead(TOUCH_PIN);
        int rssi = WiFi.RSSI();

        String payload = "{";
        payload += "\"temp\":" + String(temp, 1);
        payload += ",\"touch\":" + String(touchVal);
        payload += ",\"rssi\":" + String(rssi);
        payload += ",\"seq\":" + String(signedCount + 1);
        payload += ",\"device\":\"sensor_node_1\"";
        payload += "}";

        // Measure signing overhead
        unsigned long t0 = micros();
        bool ok = mqClient.publishSigned("secure/sensors/temperature", payload);
        unsigned long signTimeUs = micros() - t0;

        if (ok) {
            signedCount++;
            totalSignTimeUs += signTimeUs;
            Serial.printf("[SIGNED] #%u -> secure/sensors/temperature (%u bytes, %luus sign+send)\n",
                          signedCount, payload.length(), signTimeUs);
            blinkLED(30);
        } else {
            rejectCount++;
            Serial.printf("[SIGNED FAIL] #%u\n", rejectCount);
        }

        // Also publish touch events on secure topic
        if (touchVal < 40) {  // Touch detected
            String touchPayload = "{\"event\":\"touch\",\"value\":" + String(touchVal) + "}";
            mqClient.publishSigned("secure/sensors/touch", touchPayload);
            Serial.printf("[SIGNED] Touch event -> secure/sensors/touch (val=%d)\n", touchVal);
            blinkLED(100);
        }
    }

    // === UNSIGNED PUBLISH to normal topic (every 5s, for comparison) ===
    if (now - lastUnsignedPublish >= 5000) {
        lastUnsignedPublish = now;

        String payload = "{\"temp\":" + String(temperatureRead(), 1) +
                          ",\"heap\":" + String(ESP.getFreeHeap()) +
                          ",\"seq\":" + String(unsignedCount + 1) + "}";

        unsigned long t0 = micros();
        bool ok = mqClient.publish("sensors/esp32/telemetry", payload);
        unsigned long sendTimeUs = micros() - t0;

        if (ok) {
            unsignedCount++;
            Serial.printf("[UNSIGNED] #%u -> sensors/esp32/telemetry (%u bytes, %luus)\n",
                          unsignedCount, payload.length(), sendTimeUs);
        }
    }

    // === DEMO: Try unsigned publish to secure/ topic (should be REJECTED!) ===
    // Do this once at 30s mark to demonstrate security enforcement
    static bool rejectionDemoDone = false;
    if (!rejectionDemoDone && now - startTime > 30000) {
        rejectionDemoDone = true;
        Serial.println("\n╔═══════════════════════════════════════════════════╗");
        Serial.println("║  SECURITY DEMO: Attempting UNSIGNED publish to    ║");
        Serial.println("║  secure/ topic — broker should REJECT this!       ║");
        Serial.println("╚═══════════════════════════════════════════════════╝");

        bool ok = mqClient.publish("secure/sensors/temperature", "{\"forged\":true}");
        if (ok) {
            Serial.println("  >>> Sent (broker will reject at protocol level)");
        } else {
            Serial.println("  >>> Send failed");
        }
        Serial.println("");
    }

    // === HEARTBEAT (every 10s) ===
    if (now - lastHeartbeat >= 10000) {
        lastHeartbeat = now;

        float avgSignUs = signedCount > 0 ? (float)totalSignTimeUs / signedCount : 0;

        Serial.println("\n┌─── Security Publisher Stats ──────────────────┐");
        Serial.printf("│ Signed publishes:    %u\n", signedCount);
        Serial.printf("│ Unsigned publishes:  %u\n", unsignedCount);
        Serial.printf("│ Rejections:          %u\n", rejectCount);
        Serial.printf("│ Avg sign+send time:  %.0f us\n", avgSignUs);
        Serial.printf("│ Free heap:           %u bytes\n", ESP.getFreeHeap());
        Serial.printf("│ Min free heap:       %u bytes\n", ESP.getMinFreeHeap());
        if (psramFound()) {
            Serial.printf("│ PSRAM free:          %u bytes\n", ESP.getFreePsram());
        }
        Serial.printf("│ WiFi RSSI:           %d dBm\n", WiFi.RSSI());
        Serial.printf("│ Uptime:              %lus\n", millis() / 1000);
        Serial.println("└───────────────────────────────────────────────┘\n");

        // Publish heartbeat on secure topic (signed)
        String hb = "{\"up\":" + String(millis() / 1000) +
                     ",\"signed\":" + String(signedCount) +
                     ",\"unsigned\":" + String(unsignedCount) +
                     ",\"heap\":" + String(ESP.getFreeHeap()) +
                     ",\"rssi\":" + String(WiFi.RSSI()) + "}";
        mqClient.publishSigned("secure/sensors/heartbeat", hb);
    }
}

void blinkLED(int ms) {
    digitalWrite(LED_PIN, HIGH);
    delay(ms);
    digitalWrite(LED_PIN, LOW);
}
