// MetricMQ Key Generator — Generate Ed25519 keypairs for ESP32 devices
// Outputs C-style arrays ready to paste into Arduino sketches
// Also registers the public key in the broker's global keystore
//
// Usage: metricmq-keygen.exe [device_name] [allowed_topics]
// Example: metricmq-keygen.exe "sensor_node_1" "sensors/*"

#include "metricmq/crypto.hpp"
#include <iostream>
#include <iomanip>
#include <string>
#include <fstream>

int main(int argc, char* argv[]) {
    std::string device_name = (argc > 1) ? argv[1] : "esp32_device";
    std::string allowed_topics = (argc > 2) ? argv[2] : "*";

    std::cout << "=== MetricMQ Ed25519 Key Generator ===\n\n";

    // Initialize crypto
    if (!metricmq::crypto::init()) {
        std::cerr << "ERROR: Failed to initialize crypto (libsodium)\n";
        return 1;
    }

    // Generate keypair
    auto keypair = metricmq::crypto::generate_keypair();

    // Register in global keystore
    auto& keystore = metricmq::crypto::get_global_keystore();
    uint32_t key_id = keystore.register_key(keypair.public_key, device_name, allowed_topics);

    std::cout << "Device Name:    " << device_name << "\n";
    std::cout << "Allowed Topics: " << allowed_topics << "\n";
    std::cout << "Key ID:         " << key_id << "\n";
    std::cout << "Public Key:     " << metricmq::crypto::to_hex(keypair.public_key) << "\n\n";

    // Output as C arrays for ESP32 Arduino sketch
    std::cout << "// ===== PASTE INTO YOUR ARDUINO SKETCH =====\n\n";

    std::cout << "// Device: " << device_name << " | Key ID: " << key_id << "\n";
    std::cout << "// Allowed topics: " << allowed_topics << "\n";
    std::cout << "const uint32_t DEVICE_KEY_ID = " << key_id << ";\n\n";

    // Secret key (64 bytes)
    std::cout << "// Ed25519 SECRET key (64 bytes) — keep private!\n";
    std::cout << "const uint8_t DEVICE_SECRET_KEY[64] = {\n";
    for (int i = 0; i < 64; i++) {
        if (i % 12 == 0) std::cout << "    ";
        std::cout << "0x" << std::hex << std::setw(2) << std::setfill('0')
                  << static_cast<int>(keypair.secret_key[i]);
        if (i < 63) std::cout << ", ";
        if ((i + 1) % 12 == 0) std::cout << "\n";
    }
    if (64 % 12 != 0) std::cout << "\n";
    std::cout << "};\n\n";

    // Public key (32 bytes)
    std::cout << "// Ed25519 PUBLIC key (32 bytes) — share freely\n";
    std::cout << "const uint8_t DEVICE_PUBLIC_KEY[32] = {\n";
    for (int i = 0; i < 32; i++) {
        if (i % 12 == 0) std::cout << "    ";
        std::cout << "0x" << std::hex << std::setw(2) << std::setfill('0')
                  << static_cast<int>(keypair.public_key[i]);
        if (i < 31) std::cout << ", ";
        if ((i + 1) % 12 == 0) std::cout << "\n";
    }
    if (32 % 12 != 0) std::cout << "\n";
    std::cout << "};\n\n";
    std::cout << "// ===== END OF KEYS =====\n\n";

    // Also output broker registration code
    std::cout << std::dec;
    std::cout << "// ===== PASTE INTO BROKER STARTUP / REGISTRATOR =====\n";
    std::cout << "// auto& ks = metricmq::crypto::get_global_keystore();\n";
    std::cout << "// metricmq::crypto::PublicKey pk = {";
    for (int i = 0; i < 32; i++) {
        std::cout << "0x" << std::hex << std::setw(2) << std::setfill('0')
                  << static_cast<int>(keypair.public_key[i]);
        if (i < 31) std::cout << ",";
    }
    std::cout << "};\n";
    std::cout << std::dec;
    std::cout << "// ks.register_key(" << key_id << ", pk, \"" << device_name << "\", \"" << allowed_topics << "\");\n\n";

    // Save to file
    std::string filename = device_name + "_keys.h";
    std::ofstream out(filename);
    if (out.is_open()) {
        out << "// Auto-generated by metricmq-keygen\n";
        out << "// Device: " << device_name << " | Key ID: " << key_id << "\n";
        out << "// Allowed topics: " << allowed_topics << "\n\n";
        out << "#pragma once\n\n";
        out << "const uint32_t DEVICE_KEY_ID = " << key_id << ";\n\n";

        out << "const uint8_t DEVICE_SECRET_KEY[64] = {\n";
        for (int i = 0; i < 64; i++) {
            if (i % 12 == 0) out << "    ";
            out << "0x" << std::hex << std::setw(2) << std::setfill('0')
                << static_cast<int>(keypair.secret_key[i]);
            if (i < 63) out << ", ";
            if ((i + 1) % 12 == 0) out << "\n";
        }
        if (64 % 12 != 0) out << "\n";
        out << "};\n\n";

        out << "const uint8_t DEVICE_PUBLIC_KEY[32] = {\n";
        for (int i = 0; i < 32; i++) {
            if (i % 12 == 0) out << "    ";
            out << "0x" << std::hex << std::setw(2) << std::setfill('0')
                << static_cast<int>(keypair.public_key[i]);
            if (i < 31) out << ", ";
            if ((i + 1) % 12 == 0) out << "\n";
        }
        if (32 % 12 != 0) out << "\n";
        out << "};\n";

        out.close();
        std::cout << "Keys saved to: " << filename << "\n";
    }

    // Verify round-trip
    std::string test_msg = "test_topic" + std::string("test_payload");
    auto sig = metricmq::crypto::sign(test_msg, keypair.secret_key);
    bool ok = metricmq::crypto::verify(test_msg, sig, keypair.public_key);
    std::cout << "Self-test: " << (ok ? "PASSED" : "FAILED") << "\n";

    // Clean up
    metricmq::crypto::secure_zero(keypair.secret_key);

    return 0;
}
